### ISSUE TITLE
Plenty of unresolved dependencies

### ISSUE THREAD

**Issue by elmimmo** [martido/homebrew-graph#13]
Generating a graph of all installed packages results in a chart with plenty of packages as isolated leaves that in reality are dependencies of others. For example, with `ffmpeg` installed, running:

	brew graph --installed -f graphml -o deps.graphml

creates a graph with `dav1d` as an isolated node, yet,

```
$ brew deps ffmpeg
aom
bdw-gc
c-ares
cairo
dav1d
…
```

and therefore predictably, attempting to uninstall `dav1d` fails:

```
$ brew uninstall dav1d
Error: Refusing to uninstall /usr/local/Cellar/dav1d/0.8.2
because it is required by ffmpeg, mpv, ocrmypdf and unpaper, which are currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies dav1d
```

**Comment by martido** [comment]
@elmimmo What's the output when you do `brew deps --installed`? Is the dependency listed under ffmpeg? If not, please `brew upgrade` and try again. What's the output now?

I've recently had a similar situation in which `brew deps <formula>` showed a dependency that was not listed with `brew deps --installed` (which my script uses). After I updated Homebrew and all my installed formulas, it was suddenly there. I haven't been able to reproduce that situation since then, but back then I thought it might have been an issue with Homebrew itself.

**Comment by Nakilon** [comment]
Probably related: https://github.com/Homebrew/discussions/discussions/1574

**Comment by martido** [comment]
I've just had the same situation again when I did `brew deps --installed`. Lots of isolated packages and wrong dependecies. After I updated Homebrew, dependencies were fine again. This is definitely an issue with Homebrew.

**Comment by Nakilon** [comment]
@martido did upgrading the brew also upgrade your packages?

**Comment by martido** [comment]
@Nakilon No, I should have been more specific. After I updated Homebrew and then upgraded the packages, dependencies were good again.

**Comment by Nakilon** [comment]
@martido then I doubt the issue is fixed. You can see in the Discussions topic I linked that the issue happens after a while and updating packages just temporary cleans it.

**Comment by martido** [comment]
@Nakilon Ok, from that angle, I agree. Then I suggest adding a kind of info / disclaimer in the README linking to the discussion above. Or do you have a better idea?

**Comment by martido** [comment]
Just as an example, this is the first few lines of the output of `brew deps --installed` that I got before upgrading all of the dependencies:

```
brotli: 
c-ares: 
cairo: fontconfig libpng libxcb libxext libxrender lzo pixman
curl: brotli rtmpdump
fontconfig: 
freetype: libpng
fribidi: 
gd: fontconfig jpeg libpng libtiff
gdbm: 
gdk-pixbuf: jpeg libpng libtiff
gettext: 
gh: 
git: gettext
```

And this is what I got immediately after upgrading:

```
brotli: 
c-ares: 
ca-certificates: 
cairo: fontconfig freetype glib libpng libx11 libxcb libxext libxrender lzo pixman
curl: brotli libidn2 libnghttp2 libssh2 openldap openssl@1.1 rtmpdump zstd
fontconfig: freetype
freetype: libpng
fribidi: 
gd: fontconfig freetype jpeg libpng libtiff webp
gdbm: 
gdk-pixbuf: glib jpeg libpng libtiff
gettext: 
gh: 
giflib: 
git: gettext pcre2

```

This is a huge difference.

**Comment by martido** [comment]
I've added a "Known Issues" section to the README.

**Comment by michaelblyons** [comment]
I ran into this the normal way this time (not #18 with "optional" dependencies). I found `--highlight-outdated` to be helpful to note that some packages were out of date.

I still think it'd still be nice if Homebrew's `deps` output showed the right answer for actual dependencies, but that's not a problem with homebrew-graph.

**Comment by Nakilon** [comment]
Homebrew devs don't seem to track the issues, they only have a "Discussions" used as a hiding carpet.
