### ISSUE TITLE
Option to output just the roots

### ISSUE THREAD

**Issue by davidfetter** [martido/homebrew-graph#17]
Any chance there's a way to do just the roots, i.e. vertexes with in-degree 0?

This would be super handy for people who want to reproduce a setup.

**Comment by martido** [comment]
Hey @davidfetter, for that purpose, wouldn't a simple `brew list` on the command line be enough? Or could you please explain a bit more what you're trying to accomplish?

**Comment by davidfetter** [comment]
Oh, it'd be handy to get the minimal set of things to set up an environment with. There's no point listing, say `OpenSSL` when several things already depend on it.

**Comment by erikhuizinga** [comment]
I'm also interested in finding just the roots, so that I can revise what's installed and uninstall whatever I no longer use.

**Comment by martido** [comment]
From the command line you could use the built-in `brew leaves`, which will give you all installed formula that are not dependencies of another installed formula, i.e. all nodes with in-degree = 0. Similarly, in brew-graph you can use the `--highlight-leaves` option to highlight those nodes in the graph. Is that what you're looking for?

@davidfetter Sorry that it took me so long to respond. Too much going on with Covid and all.

**Comment by davidfetter** [comment]
The "leaves" options solve my problem perfectly, and thanks for pointing them out!
