### ISSUE TITLE
Support multiple formulae on CLI

### ISSUE THREAD

**Issue by michaelblyons** [martido/homebrew-graph#9]
https://github.com/martido/brew-graph/blob/98b9982916cd7438a5f19a547c2f3b8359162ead/brew-graph.rb#L130-L136

These lines and the "take only first arg" code can be updated to support multiple formulae, if you use `--union --for-each` in the arguments: `brew deps --union --for-each wget vim`.

I haven't worked out if there's a way to get hierarchical output (rather than flattened output) except with `--tree`.

**Comment by martido** [comment]
Nice idea. Right now I can't check it out because my Mac's in repair, but I will as soon as I can.

**Comment by martido** [comment]
Finally gotten around to add your suggestion. It requires a bit of string manipulation to get the output into the right shape. I'm building on the default flat output btw. Works nicely as far as I can see.
